spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/reporting}
    username: ${POSTGRES_USER:reporting}
    password: ${POSTGRES_PASSWORD:reporting}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

    elasticsearch:
      uris: ${ES_URIS:http://localhost:9200}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

logging:
  level:
    com.banking.reporting: DEBUG
    org.springframework.kafka: DEBUG
