spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: products
    password: products
  kafka:
    bootstrap-servers: localhost:29092

logging:
  level:
    com.banking.product: DEBUG
