apiVersion: v2
name: reporting-service
description: Banking Reporting Microservice Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - banking
  - reporting
  - microservice
maintainers:
  - name: Banking Platform Team
    email: platform@banking.com
