replicaCount: 1

autoscaling:
  enabled: false

config:
  kafkaBootstrapServers: "kafka.infra.svc.cluster.local:9092"
  esUris: "http://elasticsearch.infra.svc.cluster.local:9200"
  keycloakJwksUri: "http://keycloak.auth.svc.cluster.local:8080/realms/banking/protocol/openid-connect/certs"
  logLevel: "DEBUG"

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "512Mi"

podDisruptionBudget:
  enabled: false

ingress:
  hosts:
    - host: reporting-dev.banking.internal
      paths:
        - path: /api/reports
          pathType: Prefix
